// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ4UM1XXyKrURYguRR0RQqqnY2xrIEHyY',
    appId: '1:220237992971:web:fe6c96ac1373819a43a30e',
    messagingSenderId: '220237992971',
    projectId: 'seraphex-48872',
    authDomain: 'seraphex-48872.firebaseapp.com',
    storageBucket: 'seraphex-48872.firebasestorage.app',
    measurementId: 'G-XEZZ4CD8FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzRTTPYd6X8W1fIRqDAbnd4LDJv1PxelU',
    appId: '1:220237992971:android:644b39cfd4ad619e43a30e',
    messagingSenderId: '220237992971',
    projectId: 'seraphex-48872',
    storageBucket: 'seraphex-48872.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASaiR5KBswqfvve-y9nTs6I2D-CjHvJQk',
    appId: '1:220237992971:ios:da37b674142b024643a30e',
    messagingSenderId: '220237992971',
    projectId: 'seraphex-48872',
    storageBucket: 'seraphex-48872.firebasestorage.app',
    iosBundleId: 'com.example.artisanMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASaiR5KBswqfvve-y9nTs6I2D-CjHvJQk',
    appId: '1:220237992971:ios:da37b674142b024643a30e',
    messagingSenderId: '220237992971',
    projectId: 'seraphex-48872',
    storageBucket: 'seraphex-48872.firebasestorage.app',
    iosBundleId: 'com.example.artisanMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ4UM1XXyKrURYguRR0RQqqnY2xrIEHyY',
    appId: '1:220237992971:web:520eaa1c9862945443a30e',
    messagingSenderId: '220237992971',
    projectId: 'seraphex-48872',
    authDomain: 'seraphex-48872.firebaseapp.com',
    storageBucket: 'seraphex-48872.firebasestorage.app',
    measurementId: 'G-E8QMDL33H7',
  );
}
